apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: student-management
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/student_management"
  SPRING_DATASOURCE_USERNAME: "studentapp"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  MANAGEMENT_SERVER_PORT: "8089"
