apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  labels:
    app: student-management
spec:
  type: NodePort
  ports:
  - port: 8089
    targetPort: 8089
    nodePort: 30089
    protocol: TCP
    name: http
  selector:
    app: student-management
