apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: student-management
type: Opaque
data:
  # spring-datasource-password: base64 encoded "studentpass"
  spring-datasource-password: c3R1ZGVudHBhc3M=
