apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # MySQL resources
  - mysql-configmap.yaml
  - mysql-secret.yaml
  - mysql-pv.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  
  # Application resources
  - app-configmap.yaml
  - app-secret.yaml
  - app-deployment.yaml
  - app-service.yaml

namespace: default

commonLabels:
  project: student-management
  environment: development
