apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  # mysql-root-password: base64 encoded "rootpassword"
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # mysql-user: base64 encoded "studentapp"
  mysql-user: c3R1ZGVudGFwcA==
  # mysql-password: base64 encoded "studentpass"
  mysql-password: c3R1ZGVudHBhc3M=
